const PACKAGE_JSON = JSON.stringify(
  {
    name: 'my-vizzy-server',
    version: '1.0.0',
    description: 'Express server generated by Vizzy',
    main: 'server.js',
    scripts: {
      start: 'node server.js',
      dev: 'node --watch server.js',
    },
    dependencies: {
      express: '^4.18.2',
    },
  },
  null,
  2,
)

function downloadFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function exportServerFiles(serverJsContent: string, onExported?: () => void): void {
  downloadFile('server.js', serverJsContent, 'text/javascript')
  // Small delay so browsers don't block the second download as a popup
  setTimeout(() => {
    downloadFile('package.json', PACKAGE_JSON, 'application/json')
    onExported?.()
  }, 150)
}
